//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS_Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public Nullable<int> MST { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
